name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Alibaba Cloud
      run: |
        # Example of PowerShell script to copy files to the server via WinSCP
        $localPath = "dist\*"
        $remotePath = "/path/to/remote/directory"
        & 'C:\Path\To\WinSCP\WinSCP.com' /command `
          "open sftp://$env:SERVER_USER:$env:SERVER_PASSWORD@$env:SERVER_HOST/ -hostkey=`"`$env:SERVER_SSH_KEY`"" `
          "put $localPath $remotePath" `
          "exit"
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      shell: pwsh

