name: CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 根据您的需要更改版本

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Alibaba Cloud
      run: |
        # 使用Windows命令上传文件到服务器
        $username = "${{ secrets.SERVER_USER }}"
        $server = "${{ secrets.SERVER_HOST }}"
        $password = "${{ secrets.SERVER_PASSWORD }}"
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential $username, $securePassword
        $session = New-PSSession -ComputerName $server -Credential $credential
        Copy-Item -Path "./build/*" -Destination "C:/path/to/destination" -ToSession $session
        Invoke-Command -Session $session -ScriptBlock {
          cd "C:/path/to/destination"
          npm run start
        }
        Remove-PSSession -Session $session
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
